Add led and backlight support for yuga.
apq8064-mainline/linux pull request #1
Opened 2021-10-25 17:38 UTC by Wouter92

Add devicetree support for TI LM3533 LED driver.
Support LM3533 LED driver in Sony yuga DTS.

2021-10-26 06:56 UTC, okias requested changes

2021-10-26 06:56 UTC, okias commented on arch/arm/boot/dts/qcom-apq8064-sony-xperia-yuga.dts
> +				clock-frequency = <200000>;
fix formatting (tabs/spaces, it should align with original DTS)

2021-10-26 06:56 UTC, okias commented on arch/arm/boot/dts/qcom-apq8064-sony-xperia-yuga.dts
> +					regulator-min-microvolt = <2850000>;
this should go as a separate change with explanation (I guess downstream doing it as u described here)?

2021-10-26 06:56 UTC, okias commented on drivers/mfd/lm3533-core.c
> +#include <linux/of_gpio.h>
can you do also YAML documentation for it in `Documentation/devicetree/bindings/` ?

Easiest way is copy existing binding for similar mfd and adjust it, then run yamllint, and `make dt_bindings_check`

2021-10-26 11:33 UTC, okias requested changes

2021-10-26 11:33 UTC, okias commented on Documentation/devicetree/bindings/mfd/ti,lm3533.yaml
> +            hwen-gpios = <&pm8921_gpio 26 GPIO_ACTIVE_HIGH>;
`GPIO_ACTIVE_HIGH` will need include for the example

2021-10-26 11:33 UTC, okias commented on Documentation/devicetree/bindings/mfd/ti,lm3533.yaml
> +        ...
not needed dots

2021-10-26 11:33 UTC, okias commented on Documentation/devicetree/bindings/mfd/ti,lm3533.yaml
> +    += EXAMPLE
`make dt_bindings_check` will probably fails on this, remove

2021-10-26 11:33 UTC, okias commented on Documentation/devicetree/bindings/mfd/ti,lm3533.yaml
> +        description:
`>` or `|` missing (probably `>` is good choice)

... this is valid for all multiline description or other stuff

2021-10-26 13:05 UTC, wouterfranken commented on Documentation/devicetree/bindings/mfd/ti,lm3533.yaml
> +    += EXAMPLE
Strange, it did not. I will remove.

2021-10-26 13:11 UTC, wouterfranken commented on arch/arm/boot/dts/qcom-apq8064-sony-xperia-yuga.dts
> +					regulator-min-microvolt = <2850000>;
I put this in a separate commit. Should this be in a separate pull request?

2021-10-26 13:13 UTC, okias commented on arch/arm/boot/dts/qcom-apq8064-sony-xperia-yuga.dts
> +					regulator-min-microvolt = <2850000>;
separation - that's just for upstreaming, for qcom-apq8064 tree, I don't care, but when you'll be sending `git send-patch`, it has to be separate, if it's not one change.

Don't forget some brief decription why you introducing the change (even for very small changes, at least one sentence of description is required)

2021-10-30 09:39 UTC, Wouter92 commented on arch/arm/boot/dts/qcom-apq8064-sony-xperia-yuga.dts
> +					regulator-min-microvolt = <2850000>;
Ok, opened another PR with regulator changes and a brief description to every commit.

2021-10-30 10:36 UTC, merged

2021-10-30 10:36 UTC, okias commented
Thank you!